# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - development 
      - staging
      - production
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-develop:
    if: github.ref == 'refs/heads/development' # Only run this job for the develop branch
    runs-on: ubuntu-latest
    steps:
      - name: Build for Staging
        run: |
          echo "Building for development..."


  build-main:
    if: github.ref == 'refs/heads/main' # Run this job for feature branches
    runs-on: ubuntu-latest
    steps:
       - name: Run Tests
         run: |
           echo "Running tests for main"

  deploy-to-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: |
           echo "Deploying to staging..."


  deploy-to-production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
           echo "Deploying to production..."
